apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./manifests/alertmanager/alertmanager-alertmanager.yaml
- ./manifests/alertmanager/alertmanager-podDisruptionBudget.yaml
- ./manifests/alertmanager/alertmanager-prometheusRule.yaml
- ./manifests/alertmanager/alertmanager-secret.yaml
- ./manifests/alertmanager/alertmanager-service.yaml
- ./manifests/alertmanager/alertmanager-serviceAccount.yaml
- ./manifests/alertmanager/alertmanager-serviceMonitor.yaml
- ./manifests/etcd/prometheus-endpointsEtcd.yaml
- ./manifests/etcd/prometheus-rulesEtcd.yaml
- ./manifests/etcd/prometheus-secretEtcdCerts.yaml
- ./manifests/etcd/prometheus-serviceEtcd.yaml
- ./manifests/etcd/prometheus-serviceMonitorEtcd.yaml
- ./manifests/grafana/grafana-config.yaml
- ./manifests/grafana/grafana-dashboardDatasources.yaml
- ./manifests/grafana/grafana-dashboardDefinitions.yaml
- ./manifests/grafana/grafana-dashboardSources.yaml
- ./manifests/grafana/grafana-deployment.yaml
- ./manifests/grafana/grafana-service.yaml
- ./manifests/grafana/grafana-serviceAccount.yaml
- ./manifests/grafana/grafana-serviceMonitor.yaml
- ./manifests/grafana/grafana-storage.yaml
- ./manifests/kube-prometheus/kube-prometheus-prometheusRule.yaml
- ./manifests/kube-state-metrics/kube-state-metrics-clusterRole.yaml
- ./manifests/kube-state-metrics/kube-state-metrics-clusterRoleBinding.yaml
- ./manifests/kube-state-metrics/kube-state-metrics-deployment.yaml
- ./manifests/kube-state-metrics/kube-state-metrics-prometheusRule.yaml
- ./manifests/kube-state-metrics/kube-state-metrics-service.yaml
- ./manifests/kube-state-metrics/kube-state-metrics-serviceAccount.yaml
- ./manifests/kube-state-metrics/kube-state-metrics-serviceMonitor.yaml
- ./manifests/kubernetes/kubernetes-prometheusRule.yaml
- ./manifests/kubernetes/kubernetes-serviceKubeControllerManager.yaml
- ./manifests/kubernetes/kubernetes-serviceKubeScheduler.yaml
- ./manifests/kubernetes/kubernetes-serviceMonitorApiserver.yaml
- ./manifests/kubernetes/kubernetes-serviceMonitorCoreDNS.yaml
- ./manifests/kubernetes/kubernetes-serviceMonitorKubeControllerManager.yaml
- ./manifests/kubernetes/kubernetes-serviceMonitorKubeScheduler.yaml
- ./manifests/kubernetes/kubernetes-serviceMonitorKubelet.yaml
- ./manifests/node-exporter/node-exporter-clusterRole.yaml
- ./manifests/node-exporter/node-exporter-clusterRoleBinding.yaml
- ./manifests/node-exporter/node-exporter-daemonset.yaml
- ./manifests/node-exporter/node-exporter-prometheusRule.yaml
- ./manifests/node-exporter/node-exporter-service.yaml
- ./manifests/node-exporter/node-exporter-serviceAccount.yaml
- ./manifests/node-exporter/node-exporter-serviceMonitor.yaml
- ./manifests/prometheus-operator/prometheus-operator-0alertmanagerConfigCustomResourceDefinition.yaml
- ./manifests/prometheus-operator/prometheus-operator-0alertmanagerCustomResourceDefinition.yaml
- ./manifests/prometheus-operator/prometheus-operator-0podmonitorCustomResourceDefinition.yaml
- ./manifests/prometheus-operator/prometheus-operator-0probeCustomResourceDefinition.yaml
- ./manifests/prometheus-operator/prometheus-operator-0prometheusCustomResourceDefinition.yaml
- ./manifests/prometheus-operator/prometheus-operator-0prometheusruleCustomResourceDefinition.yaml
- ./manifests/prometheus-operator/prometheus-operator-0servicemonitorCustomResourceDefinition.yaml
- ./manifests/prometheus-operator/prometheus-operator-0thanosrulerCustomResourceDefinition.yaml
- ./manifests/prometheus-operator/prometheus-operator-clusterRole.yaml
- ./manifests/prometheus-operator/prometheus-operator-clusterRoleBinding.yaml
- ./manifests/prometheus-operator/prometheus-operator-deployment.yaml
- ./manifests/prometheus-operator/prometheus-operator-prometheusRule.yaml
- ./manifests/prometheus-operator/prometheus-operator-service.yaml
- ./manifests/prometheus-operator/prometheus-operator-serviceAccount.yaml
- ./manifests/prometheus-operator/prometheus-operator-serviceMonitor.yaml
- ./manifests/prometheus/prometheus-clusterRole.yaml
- ./manifests/prometheus/prometheus-clusterRoleBinding.yaml
- ./manifests/prometheus/prometheus-podDisruptionBudget.yaml
- ./manifests/prometheus/prometheus-prometheus.yaml
- ./manifests/prometheus/prometheus-prometheusRule.yaml
- ./manifests/prometheus/prometheus-roleBindingConfig.yaml
- ./manifests/prometheus/prometheus-roleConfig.yaml
- ./manifests/prometheus/prometheus-service.yaml
- ./manifests/prometheus/prometheus-serviceAccount.yaml
- ./manifests/prometheus/prometheus-serviceMonitor.yaml
- ./manifests/thanos-ruler/thanos-ruler-podDisruptionBudget.yaml
- ./manifests/thanos-ruler/thanos-ruler-prometheusRule.yaml
- ./manifests/thanos-ruler/thanos-ruler-service.yaml
- ./manifests/thanos-ruler/thanos-ruler-serviceMonitor.yaml
- ./manifests/thanos-ruler/thanos-ruler-thanosRuler.yaml
